### ISSUE TITLE
Too many log messages?

### ISSUE THREAD

**Issue by smungee** [hierynomus/scalariform-gradle-plugin#5]
This extension logs the `Setting Scalariform preference` messages at `lifecycle` level, which means that by default we get a lot of messages printed on the screen when we run gradle. Is there any easy way to silence these?

**Comment by smungee** [comment]
Found the solution to this. Adding the following line to the scalariform block fixes this for me..

```
 scalariform {
       logging.level = LogLevel.WARN
       ...
}
```

**Comment by hierynomus** [comment]
I've now made the loglevel `INFO`. Will be available in next release. Thanks for noticing I left that behind when I was testing it.
