### ISSUE TITLE
gradle plugin file not found

### ISSUE THREAD

**Issue by tldeti** [hierynomus/scalariform-gradle-plugin#9]
file list shows up at 
https://plugins.gradle.org/m2/gradle/plugin/com/hierynomus/gradle/plugins/scalariform-gradle-plugin/0.3.0/
but 
https://plugins.gradle.org/m2/gradle/plugin/com/hierynomus/gradle/plugins/scalariform-gradle-plugin/0.3.0/scalariform-gradle-plugin-0.3.0.pom
actually show NoSuchKey error xml.

**Comment by machaval** [comment]
Is there any chance we could have a new release of this plugin. It looks like it hasn't been published correctly

**Comment by machaval** [comment]
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
gradle.plugin.com.hierynomus.gradle.plugins/scalariform-gradle-plugin/0.3.0/8518b15fec897aa3f5cc24d4c4d09c07262c1bb908a308aa1ef1509d4df4b783/scalariform-gradle-plugin-0.3.0.pom
</Key>
<RequestId>E8A9827913A4A560</RequestId>
<HostId>
XQQp7NdwQiDUGivrZuQ7zuwqLMs30wCkDfcbAQfLT7UvQ7uBPbnNx06BD+ANCQYsD9+ltN9ij+o=
</HostId>
</Error>
```


When trying to access 
https://plugins-artifacts.gradle.org/gradle.plugin.com.hierynomus.gradle.plugins/scalariform-gradle-plugin/0.3.0/8518b15fec897aa3f5cc24d4c4d09c07262c1bb908a308aa1ef1509d4df4b783/scalariform-gradle-plugin-0.3.0.pom

**Comment by hierynomus** [comment]
Just published 0.4.0, can you check?

**Comment by machaval** [comment]
Works perfect thanks

**Comment by hierynomus** [comment]
Closing this issue
